{"uuid": "bb71fb61-c0e8-4218-9994-930a2f971e6b", "children": ["c8c11aed-2cc3-43e9-b0ec-d051b6387690", "f7e40fab-5079-4b75-a2bd-3eaa02790364", "384a447a-4a46-4977-b56d-345668059dbd"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up\n\n", "trace": "  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/_pytest/python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/_pytest/python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/mac/PycharmProjects/pytest_demos/scripts/test_demo.py\", line 15, in setup_class\n    self.driver = init_driver_calculator()\n  File \"/Users/mac/Desktop/project/base/base_driver.py\", line 29, in init_driver_calculator\n    return init_driver(\"com.android.calculator2\", \"com.android.calculator2.Calculator\")\n  File \"/Users/mac/Desktop/project/base/base_driver.py\", line 23, in init_driver\n    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 147, in __init__\n    super(WebDriver, self).__init__(\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 227, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/mac/PycharmProjects/pytest_demos/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1587123381773, "stop": 1587123423530}], "start": 1587123381773, "stop": 1587123424747}